### ISSUE TITLE
Use local variables when rendering templates

### ISSUE THREAD

**Issue by tadast** [alphagov/smart-answers#1744]
As discussed [here](https://github.com/alphagov/smart-answers/pull/1742#issuecomment-114912740) some erb partials we use reference a lot of instance variables. Consider [passing in local variables](http://rails-bestpractices.com/posts/2010/07/24/replace-instance-variable-with-local-variable/) instead.

**Comment by chrisroos** [comment]
I'm actually going to address this in a new commit on #1737.

[Your comment about `@state` changing][1] reminded me that we're instantiating the `OutcomePresenter` multiple times in the '_result.html.erb' partial (because `SmartAnswerPresenter#current_node` returns new instances each time). I can avoid the multiple instantiation, the use of instance variables, and (I think) address your concern about `@state` changing by passing the `OutcomePresenter` to the '_result.html.erb' partial in the `locals` hash.

[1]: https://github.com/alphagov/smart-answers/pull/1737#discussion_r33148912

**Comment by floehopper** [comment]
:+1:
